### ISSUE TITLE
Infrastructure Upgrade

### ISSUE THREAD

**Issue by raynigon** [brose-ebike/cloud-status#19]
We need to upgrade our drive unit for the E-Bike cloud.
To ensure we will climb every mountain with you in the future, 
we need to increase torque, pump up the battery capacity and pressurizes the tires.

**Comment by raynigon** [comment]
At 21:00 CET we will shut down the E-Bike Cloud for a few minutes. @niclas-raabe

**Comment by raynigon** [comment]
We started a few minutes later, because some of you were still on your way home ;)

**Comment by niclas-raabe** [comment]
And we are back online. Took a bit longer than expected but not we are running with better performance :)
